let divOne = [
  {
    id: "",
    ruLowCase: "ё",
    ruUpperCase: "Ё",
    enLowCase: "'",
    enUpperCase: "~",
  },
  {
    id: "",
    ruLowCase: "1",
    ruUpperCase: "!",
    enLowCase: "1",
    enUpperCase: "!",
  },
  {
    id: "",
    ruLowCase: "2",
    ruUpperCase: '"',
    enLowCase: "2",
    enUpperCase: "@",
  },
  {
    id: "",
    ruLowCase: "3",
    ruUpperCase: "№",
    enLowCase: "3",
    enUpperCase: "#",
  },
  {
    id: "",
    ruLowCase: "4",
    ruUpperCase: ";",
    enLowCase: "4",
    enUpperCase: "$",
  },
  {
    id: "",
    ruLowCase: "5",
    ruUpperCase: "%",
    enLowCase: "5",
    enUpperCase: "%",
  },
  {
    id: "",
    ruLowCase: "6",
    ruUpperCase: ":",
    enLowCase: "6",
    enUpperCase: "^",
  },
  {
    id: "",
    ruLowCase: "7",
    ruUpperCase: "?",
    enLowCase: "7",
    enUpperCase: "&",
  },
  {
    id: "",
    ruLowCase: "8",
    ruUpperCase: "*",
    enLowCase: "8",
    enUpperCase: "*",
  },
  {
    id: "",
    ruLowCase: "9",
    ruUpperCase: "(",
    enLowCase: "9",
    enUpperCase: "(",
  },
  {
    id: "",
    ruLowCase: "0",
    ruUpperCase: ")",
    enLowCase: "0",
    enUpperCase: ")",
  },
  {
    id: "",
    ruLowCase: "-",
    ruUpperCase: "_",
    enLowCase: "-",
    enUpperCase: "_",
  },
  {
    id: "",
    ruLowCase: "=",
    ruUpperCase: "+",
    enLowCase: "=",
    enUpperCase: "+",
  },
  {
    id: "",
    text: "Backspace",
  },
];

let divTwo = [
  {
    id: "",
    text: "Tab",
  },
  {
    id: "",
    ruLowCase: "й",
    ruUpperCase: "Й",
    enLowCase: "q",
    enUpperCase: "Q",
  },
  {
    id: "",
    ruLowCase: "ц",
    ruUpperCase: "Ц",
    enLowCase: "w",
    enUpperCase: "W",
  },
  {
    id: "",
    ruLowCase: "у",
    ruUpperCase: "У",
    enLowCase: "e",
    enUpperCase: "E",
  },
  {
    id: "",
    ruLowCase: "к",
    ruUpperCase: "К",
    enLowCase: "r",
    enUpperCase: "R",
  },
  {
    id: "",
    ruLowCase: "е",
    ruUpperCase: "Е",
    enLowCase: "t",
    enUpperCase: "T",
  },
  {
    id: "",
    ruLowCase: "н",
    ruUpperCase: "Н",
    enLowCase: "y",
    enUpperCase: "Y",
  },
  {
    id: "",
    ruLowCase: "г",
    ruUpperCase: "Г",
    enLowCase: "u",
    enUpperCase: "U",
  },
  {
    id: "",
    ruLowCase: "ш",
    ruUpperCase: "Ш",
    enLowCase: "i",
    enUpperCase: "I",
  },
  {
    id: "",
    ruLowCase: "щ",
    ruUpperCase: "Щ",
    enLowCase: "o",
    enUpperCase: "O",
  },
  {
    id: "",
    ruLowCase: "з",
    ruUpperCase: "З",
    enLowCase: "p",
    enUpperCase: "P",
  },
  {
    id: "",
    ruLowCase: "х",
    ruUpperCase: "Х",
    enLowCase: "[",
    enUpperCase: "{",
  },
  {
    id: "",
    ruLowCase: "ъ",
    ruUpperCase: "Ъ",
    enLowCase: "]",
    enUpperCase: "}",
  },
  {
    id: "",
    ruLowCase: "\\",
    ruUpperCase: "/",
    enLowCase: "\\",
    enUpperCase: "|",
  },
  {
    id: "",
    text: "Del",
  },
];
